debug = false

logLevel = "ERROR"

[retry]

# Enable Docker Provider.
[docker]

# Default base domain used for the frontend rules.
# Can be overridden by setting the "traefik.domain" label on a services.
domain = "docker.localhost"

# Enable watch docker changes.
watch = true

# Expose services by default in Traefik.
exposedByDefault = false

network = "web"